---
# This file is managed centrally by modulesync
#   https://github.com/katello/foreman-installer-modulesync
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
env:
  - PUPPET_VERSION=3.5
  - PUPPET_VERSION=3.8
bundler_args: --without development
sudo: false
